micronaut:
    application:
        name: micronaut
    server:
        port: 8080

datasources:
    default:
        url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: ${JDBC_USER:sa}
        password: ${JDBC_PASSWORD:""}
        driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
    default:
        packages-to-scan:
            - 'br.com.alex.web.benchmark.micronaut.entity'
        properties:
            hibernate:
                hbm2ddl:
                    auto: create-drop
                show_sql: true
